### ISSUE TITLE
post-install.py cannot be python3

### ISSUE THREAD

**Issue by frozencemetery** [Tiboris/ipa-experimental-x509-auth-plugin#1]
Hi, I was testing out the newest version of this (from the COPR) and ran in to some issues.  Basically, it's a violation of both Fedora and RHEL policy for this to be python3: it should have `#!/usr/bin/python`, and if it's runnable with python3 that's a bonus.  In particular, python3 modules are not packaged for rhel7.  This results in the following error:

```
Running transaction
  Installing : ipa-experimental-x509-auth-plugin-1.1-1.el7.centos.noarch   1/1 
Traceback (most recent call last):
  File "/usr/sbin/ipa-experimental-x509-auth-enable", line 5, in <module>
    import SSSDConfig
ImportError: No module named 'SSSDConfig'
warning: %post(ipa-experimental-x509-auth-plugin-1.1-1.el7.centos.noarch) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package ipa-experimental-x509-auth-plugin-1.1-1.el7.centos.noar
ch
```

However, the file as it is written today is not python2-compliant:

```
# python /usr/sbin/ipa-experimental-x509-auth-enable 
  File "/usr/sbin/ipa-experimental-x509-auth-enable", line 25
    print("Execution of " + cmd + " failed: " + str(e), file=sys.stderr)
                                                            ^
SyntaxError: invalid syntax
```

Thanks!

**Comment by Tiboris** [comment]
+1 and fixed
Thanx
